# Sample configuration.
# See https://prometheus.io/docs/alerting/configuration/ for documentation.
---

global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: '127.0.0.1:25'
  smtp_from: 'Local Prometheus <prometheus@localhost>'
  smtp_require_tls: false

# The directory from which notification templates are read.
templates:
  - '/etc/prometheus/alertmanager_templates/*.tmpl'

# basically grabbed from GitLab CE
route:
  receiver: default-receiver
  routes: []

receivers:
  - name: default-receiver
    email_configs:
      - to: 'root@localhost'
        send_resolved: true  # send e-mail on resolved alerts

inhibit_rules: []
